### ISSUE TITLE
SGI-Reborn Broken With New Patch 8.0.1

### ISSUE THREAD

**Issue by Buckyx55** [Elfmagi/SuperGuildInviteReborn#10]
First and foremost want to say thank you for your contributions, without your efforts, many of our guilds (including my own) wouldn't exist. So thank you. I've copied the error report for you to view.
``Date: 2018-07-18 12:54:12
ID: 21
Error occured in: Global
Count: 1
Message: ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua line 1325:
   attempt to index field 'L' (a nil value)
Debug:
   ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1325:
      ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1281
   ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1671: ShowOptions()
   ...face\AddOns\SuperGuildInviteReborn\core\SGI_Core.lua:153: ?()
   ..\FrameXML\ChatFrame.lua:4715: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4383: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4419: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
backdrop = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Gold-Background"
 tileSize = 16
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Gold-Border"
 tile = true
 edgeSize = 16
 insets = <table> {
 }
}
close = <unnamed> {
 0 = <userdata>
}
anchor = <table> {
 yOfs = -50
 xOfs = 7
 point = "TOPLEFT"
 relativePoint = "TOPLEFT"
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = SGI_Options {
 0 = <userdata>
 optionHelpText = <unnamed> {
 }
 title = <unnamed> {
 }
 bottom = <unnamed> {
 }
}
(*temporary) = "TOP"
(*temporary) = 100
(*temporary) = -40
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'L' (a nil value)"
SetFramePosition = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:79
SaveFramePosition = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:108
CreateDropDown = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:44
CreateCheckbox = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:25
CreateButton = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:8
ShowWhisperFrame = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:537
OptBtn2_OnClick = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1275
KeyHarvestFrame = SGI_KeyHarvestFrame {
 0 = <userdata>
 text = <unnamed> {
 }
 GetNewKeybindKey = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:380
}
SSBtn3_OnClick = <function> defined `@Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:239`

**Comment by Elfmagi** [comment]
Could you please post the SuperGuildInviteReborn.toc file here?

**Comment by Buckyx55** [comment]
https://wow.curseforge.com/projects/superguildinvite-reborn

this is the entire file that I'm using. I can't give you the individual file cause I am at work, but can re-upload later tonight when I'm off. Thanks for the reply elfmagi! Look forward to the update/fix.

**Comment by Elfmagi** [comment]
I am assuming you're using v7.7.0.2, which is the release, correct? or are you using the beta file v8.0.0

**Comment by Buckyx55** [comment]
Yes I am using the v7.7.0.2 release on CurseForge. None of the files on GitHub. Should I use the ones on GitHub and not on CurseForge? I just saw you committed some changes.

**Comment by ada-justin** [comment]
From the commits I saw he is still updating strings. He just finished the Chat System changes.

**Comment by Elfmagi** [comment]
Yeah Still working, definitely wouldn't use current github though, I am fixing an auto disconnect atm

**Comment by Buckyx55** [comment]
I know you said you were still working but I just launched it with the Github version (with the most recent commits) and am getting these errors now. (I assume you're still working on these, but I just wanted you to get an updated code version so you could see).  THANKS AGAIN. You're literally the best.

`Date: 2018-07-18 18:56:38
ID: 17
Error occured in: Global
Count: 1
Message: ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua line 1328:
   attempt to index field 'L' (a nil value)
Debug:
   ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1328:
      ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1284
   ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1674: ShowOptions()
   ...face\AddOns\SuperGuildInviteReborn\core\SGI_Core.lua:153: ?()
   ..\FrameXML\ChatFrame.lua:4715: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4383: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4419: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
backdrop = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Gold-Background"
 tileSize = 16
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Gold-Border"
 tile = true
 edgeSize = 16
 insets = <table> {
 }
}
close = <unnamed> {
 0 = <userdata>
}
anchor = <table> {
 yOfs = -50
 xOfs = 7
 point = "TOPLEFT"
 relativePoint = "TOPLEFT"
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = SGI_Options {
 0 = <userdata>
 optionHelpText = <unnamed> {
 }
 title = <unnamed> {
 }
 bottom = <unnamed> {
 }
}
(*temporary) = "TOP"
(*temporary) = 100
(*temporary) = -40
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = "SGI_Options"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'L' (a nil value)"
SetFramePosition = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:79
SaveFramePosition = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:108
CreateDropDown = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:44
CreateCheckbox = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:25
CreateButton = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:8
ShowWhisperFrame = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:537
OptBtn2_OnClick = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1278
KeyHarvestFrame = SGI_KeyHarvestFrame {
 0 = <userdata>
 text = <unnamed> {
 }
 GetNewKeybindKey = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:380
}
SSBtn3_OnClick = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:239`

**Comment by Buckyx55** [comment]
Thank you for committing those changes @Elfmagi When I get home tonight I'll install and check it out. HOpefully it's all resolved. Thanks again for your hard work!!

**Comment by Elfmagi** [comment]
I'll try also tonight, I'm stuck at work right now so no access to the game

**Comment by Buckyx55** [comment]
@Elfmagi Still appears to be broken somewhere. Here is the updated code when I type in /sgi options 

`Date: 2018-07-19 16:45:14
ID: 18
Error occured in: Global
Count: 1
Message: ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua line 1328:
   attempt to index field 'L' (a nil value)
Debug:
   ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1328:
      ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1284
   ...rface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1674: ShowOptions()
   ...face\AddOns\SuperGuildInviteReborn\core\SGI_Core.lua:153: ?()
   ..\FrameXML\ChatFrame.lua:4715: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4383: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4419: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
backdrop = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Gold-Background"
 tileSize = 16
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Gold-Border"
 tile = true
 edgeSize = 16
 insets = <table> {
 }
}
close = <unnamed> {
 0 = <userdata>
}
anchor = <table> {
 yOfs = -50
 xOfs = 7
 point = "TOPLEFT"
 relativePoint = "TOPLEFT"
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = SGI_Options {
 0 = <userdata>
 optionHelpText = <unnamed> {
 }
 title = <unnamed> {
 }
 bottom = <unnamed> {
 }
}
(*temporary) = "TOP"
(*temporary) = 100
(*temporary) = -40
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = "SGI_Options"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'L' (a nil value)"
SetFramePosition = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:79
SaveFramePosition = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:108
CreateDropDown = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:44
CreateCheckbox = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:25
CreateButton = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:8
ShowWhisperFrame = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:537
OptBtn2_OnClick = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:1278
KeyHarvestFrame = SGI_KeyHarvestFrame {
 0 = <userdata>
 text = <unnamed> {
 }
 GetNewKeybindKey = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:380
}
SSBtn3_OnClick = <function> defined @Interface\AddOns\SuperGuildInviteReborn\core\SGI_GUI.lua:239`

The minimap icon also still isn't appearing. And here is an image of what it looks like when I do /sgi options https://imgur.com/a/tzpg4HE

**Comment by Buckyx55** [comment]
Current build is working. Thank you!
